
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
=======
name: fibbot
description: an action to confirm hello world printed on logs

inputs:
  enable_fib:
    description: "variable verifies if fib-program is enabled or not"
    required: false
    default: true
  max_threshold: 
    description: "provides the max fib value to be used for fib-program"
    required: true
    default: '10000'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }} 