name: Integration Tests
on: [push, pull_request]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and run action
        id: run-action
        run: |
          docker build -t my_math_action .
          docker run --rm my_math_action 10 5
      - name: Check outputs
        run: |
          echo "Sum: ${{ steps.run-action.outputs.sum }}"
          echo "Difference: ${{ steps.run-action.outputs.difference }}"
 
