name: Integration Tests
on: 
 push:
 pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

# permissions: [opened, synchronize]
jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
#      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run action
        uses: ./
        with:
          enable_fib: true
          max_threshold: 237
          pr_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


